<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>TeamLauncher.ico</ApplicationIcon>
    <Version>3.5.8</Version>
    <AssemblyVersion>3.5.8</AssemblyVersion>
    <FileVersion>3.5.8</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="default.env" />
  </ItemGroup>

</Project>